apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  TARGET_HOSTNAME: "your hostname"
  GOOGLE_USER: "your ddns user"
  GOOGLE_PASS: "your ddns pass"
  SENTRY_URI: "your sentry uri"